import type { Transaction } from "../../types/transaction"

export const expenseCategories = [
  "Alimentación",
  "Compras",
  "Educación",
  "Ocio",
  "Otros",
  "Salud",
  "Servicios",
  "Transporte",
  "Vivienda",
]

export const transactionCategories = [
  "Todas",
  "Ingresos",
  ...expenseCategories,
]

export const transactions: Transaction[] = [
  {
    id: 1,
    description: "Sueldo mensual",
    category: "Ingresos",
    amount: 2500,
    date: "2026-07-01",
    type: "income",
  },
  {
    id: 2,
    description: "Supermercado",
    category: "Alimentación",
    amount: 85.4,
    date: "2026-07-03",
    type: "expense",
  },
  {
    id: 3,
    description: "Farmacia",
    category: "Salud",
    amount: 32.75,
    date: "2026-07-04",
    type: "expense",
  },
  {
    id: 4,
    description: "Servicio de internet",
    category: "Servicios",
    amount: 45,
    date: "2026-07-05",
    type: "expense",
  },
  {
    id: 5,
    description: "Trabajo freelance",
    category: "Ingresos",
    amount: 420,
    date: "2026-07-06",
    type: "income",
  },
  {
    id: 6,
    description: "Transporte",
    category: "Transporte",
    amount: 18.5,
    date: "2026-07-07",
    type: "expense",
  },
  {
    id: 7,
    description: "Netflix",
    category: "Ocio",
    amount: 15.49,
    date: "2026-07-08",
    type: "expense",
  },
  {
    id: 8,
    description: "Verdulería",
    category: "Alimentación",
    amount: 24.3,
    date: "2026-07-09",
    type: "expense",
  },
  {
    id: 9,
    description: "Medicamentos",
    category: "Salud",
    amount: 41.9,
    date: "2026-07-10",
    type: "expense",
  },
  {
    id: 10,
    description: "Alquiler",
    category: "Vivienda",
    amount: 650,
    date: "2026-07-11",
    type: "expense",
  },
  {
    id: 11,
    description: "Venta de equipo usado",
    category: "Ingresos",
    amount: 180,
    date: "2026-07-12",
    type: "income",
  },
  {
    id: 12,
    description: "Pedido de comida",
    category: "Alimentación",
    amount: 28.75,
    date: "2026-07-13",
    type: "expense",
  },
  {
    id: 13,
    description: "Electricidad",
    category: "Servicios",
    amount: 67.8,
    date: "2026-07-14",
    type: "expense",
  },
  {
    id: 14,
    description: "Compra de ropa",
    category: "Compras",
    amount: 95,
    date: "2026-07-15",
    type: "expense",
  },
  {
    id: 15,
    description: "Reintegro bancario",
    category: "Ingresos",
    amount: 35.5,
    date: "2026-07-16",
    type: "income",
  },
  {
    id: 16,
    description: "Veterinaria",
    category: "Otros",
    amount: 58.2,
    date: "2026-07-16",
    type: "expense",
  },
  {
    id: 17,
    description: "Curso de programación",
    category: "Educación",
    amount: 22.4,
    date: "2026-07-17",
    type: "expense",
  },
  {
    id: 18,
    description: "Suscripción de software",
    category: "Servicios",
    amount: 29.99,
    date: "2026-07-17",
    type: "expense",
  },
]

export const transactionTypes = [
  {
    label: "Todos",
    value: "all",
  },
  {
    label: "Ingresos",
    value: "income",
  },
  {
    label: "Gastos",
    value: "expense",
  },
]