name: Deploy Frontend to OCI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar a la VM de OCI y actualizar
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            cd /home/ubuntu/G9-FinanceAI-Team29/frontend
            git pull origin main
            npm install
            npm run build
            sudo pm2 restart frontend
            sleep 3
            pm2 status frontend | grep -q online || (echo "El proceso frontend no quedó online" && exit 1)